<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>AmpConfigDll</RootNamespace>
    <AssemblyName>AmpConfigDll</AssemblyName>
    <OutputPath>..\Build\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo> <!-- Assuming Properties\AssemblyInfo.cs contains custom attributes -->
  </PropertyGroup>

</Project>